spring:
  datasource:
    url: jdbc:mysql://192.168.31.128:3306/tensquare_base?autoReconnect=true&failOverReadOnly=false&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
  dbcp2:
     validation-query: SELECT 1
     test-while-idle: true
     time-between-eviction-runs-millis: 300000
     num-tests-per-eviction-run: 50
     min-evictable-idle-time-millis: 3600000
  jpa:
    hibernate:
      dll-auto: update
      format_sql: true
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update

server:
  port: 9001