spring:
  datasource:
    url: jdbc:mysql://192.168.31.128:3306/tensquare_recruit?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    dbcp2:
      time-between-eviction-runs-millis: 18800
  jpa:
    hibernate:
      dll-auto: update
      format_sql: true
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update

server:
  port: 9002